### ISSUE TITLE
image thread

### ISSUE THREAD

**Issue by sg-s** [sg-s/crabsort#1]
![image](https://user-images.githubusercontent.com/6005346/34060825-71d11a74-e1b3-11e7-9fcd-dba33f85561c.png)

**Comment by sg-s** [comment]
![untitled mov](https://user-images.githubusercontent.com/6005346/35454557-80c6ac9c-029c-11e8-881b-246e0d992307.gif)

**Comment by sg-s** [comment]
![find_spikes mov](https://user-images.githubusercontent.com/6005346/36066160-3e672d94-0e73-11e8-917e-2838e574955d.gif)

**Comment by sg-s** [comment]
<img width="832" alt="dim_red" src="https://user-images.githubusercontent.com/6005346/36075850-5865b922-0f22-11e8-82bc-dbcae7cda8c7.png">

**Comment by sg-s** [comment]
![modify mov](https://user-images.githubusercontent.com/6005346/36075988-5bd2f6fe-0f24-11e8-9703-76b5c46ff341.gif)

**Comment by MaraRue** [comment]
<img width="428" alt="Screen Shot 2020-05-11 at 9 55 30 AM" src="https://user-images.githubusercontent.com/25936954/81571153-934a6280-936f-11ea-8a67-fe88318a289d.png">

**Comment by MaraRue** [comment]
<img width="144" alt="Screen Shot 2020-05-11 at 9 55 30 AM" src="https://user-images.githubusercontent.com/25936954/81573226-313f2c80-9372-11ea-96d9-0da81e36a63a.png">

**Comment by MaraRue** [comment]
![image](https://user-images.githubusercontent.com/25936954/81573838-086b6700-9373-11ea-98fa-a7b917ced632.png)

**Comment by MaraRue** [comment]
<img width="1259" alt="Screen Shot 2020-05-11 at 10 35 52 AM" src="https://user-images.githubusercontent.com/25936954/81573987-36e94200-9373-11ea-96aa-10e6f9d09e8e.png">

**Comment by MaraRue** [comment]
![image](https://user-images.githubusercontent.com/25936954/81575100-a1e74880-9374-11ea-9a25-8b022f63453e.png)

**Comment by MaraRue** [comment]
![image](https://user-images.githubusercontent.com/25936954/81575552-2a65e900-9375-11ea-85f2-5bbde894f96e.png)

**Comment by MaraRue** [comment]
![image](https://user-images.githubusercontent.com/25936954/81576338-22f30f80-9376-11ea-9ed1-53335c289730.png)

**Comment by MaraRue** [comment]
![image](https://user-images.githubusercontent.com/25936954/81576629-7cf3d500-9376-11ea-8b25-e5d4a0171a85.png)

**Comment by MaraRue** [comment]
![Screen Shot 2020-05-11 at 10 59 16 AM](https://user-images.githubusercontent.com/25936954/81576776-a90f5600-9376-11ea-866e-c7b7b54123c8.png)

**Comment by MaraRue** [comment]
![Screen Shot 2020-05-11 at 11 02 21 AM](https://user-images.githubusercontent.com/25936954/81577045-fd1a3a80-9376-11ea-9506-186408baa930.png)

**Comment by MaraRue** [comment]
![image](https://user-images.githubusercontent.com/25936954/81581458-c3e4c900-937c-11ea-9652-31626013f2d5.png)
