### ISSUE TITLE
Pressing p should do nothing if there is no net

### ISSUE THREAD

**Issue by Wmdhampton** [sg-s/crabsort#203]
When I accidentally hit <p> after the "Cluster & Sort" phase rather than g all of my data is thrown out. It would be nice if that did not happen. Maybe make <p> do nothing when there is no NN.

**Comment by Wmdhampton** [comment]
When I accidentally hit p

after the "Cluster & Sort" phase rather than g all of my data is thrown out. It would be nice if that did not happen. Maybe make p

do nothing when there is no NN.

**Comment by sg-s** [comment]
It does nothing if network can't be found.
