### ISSUE TITLE
Manual Override default

### ISSUE THREAD

**Issue by Wmdhampton** [sg-s/crabsort#206]
I think it makes more sense to have this be 'add' rather than off. Having off as an option may not even make sense ever. My reasoning is that right clicking is always the equivalent of 'off'. Several times when I've reloaded crabsort, I've left clicked in the 'off' position by accident. By the time I realize what I've done the damage to my NN is devastating. Additionally it would be nice to be able to reset to a previous NN (maybe save the starting NN until the next file is selected).

**Comment by sg-s** [comment]
>  Several times when I've reloaded crabsort, I've left clicked in the 'off' position by accident.

That's why the default is "off" -- left clicking in off does little.

**Comment by Wmdhampton** [comment]
Left clicking in off does just as much as left clicking when on. It just does something different, and generally not what you want it too. I had to throw out the NN the last time this happened bc it was faster retrain a brand new one.

**Comment by sg-s** [comment]
but making the default "add" makes it worse because left clicking will add a new spike
