### ISSUE TITLE
overhaul plugin architecture

### ISSUE THREAD

**Issue by sg-s** [sg-s/crabsort#230]
- [x] plugins shouldn't be class methods
- [x] it should be possible for plugins to exist anywhere on the MATLAB path, but it should be easy to find them (how?)

**Comment by sg-s** [comment]
The way to do this is to have many different `+crabsortplugin` folders, all of them on path, and use 

```
a = what('crabsortplugin')
```

to find them all

**Comment by sg-s** [comment]
But `what` doesn't work with nested packages...so they will all have to live in 

```
+crabsortplugins
```

**Comment by alec-hoyland** [comment]
Revamped UMAP and FIt-SNE plugins, here: 
https://github.com/sg-s/umap-matlab-wrapper/pull/3
and here:
https://github.com/alec-hoyland/crabsort-FItSNE

**Comment by sg-s** [comment]
Amazing. I trust you have tested it against the new branch of crabsort?

**Comment by alec-hoyland** [comment]
Let me kick the tires for a bit more. I'll let you know when I'm satisfied that it works.
