### ISSUE TITLE
Link to video tutorial is inaccessible without an authorized Google account

### ISSUE THREAD

**Issue by cosmojg** [sg-s/crabsort#274]
I was trying to explain Crabsort's UI design to a coworker today, and I was momentarily excited to see that Mara had made a video tutorial before having my dreams crushed by our corporate overlords. Since I don't have a MATLAB license, I ended up resorting to the ol' marker-and-whiteboard-with-wavy-hand-gestures maneuver.

Anyway, reuploading the video to YouTube (or equivalent) should do the trick. Maybe leave it unlisted as well, and link to it directly from the README.

**Comment by sg-s** [comment]
@klwadland can you do this?

**Comment by sg-s** [comment]
yeah i can't access it either. @klwadland did you delete it?
